export const environment = {
  production: false,
  integravidaProviderApiBaseUrl: 'https://integravida-data.onrender.com',
  integravidaBackendApiBaseUrl: 'http://localhost:8096',
  integravidaBackendProfilesEndpointPath: '/api/v1/profiles',
  integravidaBackendAppointmentsEndpointPath: '/api/v1/appointments',
  integravidaProviderUsersEndpointPath: '/users',
  integravidaProviderPatientsEndpointPath: '/patients',
  integravidaProviderDoctorEndpointPath: '/doctor',
  integravidaProviderPatientDoctorEndpointPath: '/patientDoctor',
  integravidaProviderGlucoseRecordsEndpointPath: '/glucoseRecords',
  integravidaProviderSymtomsEndpointPath: '/symtoms',
  integravidaProviderMedicalHistoryEndpointPath: '/medicalHistory',
  integravidaProviderTreatmentsEndpointPath: '/treatments',
  integravidaProviderMedicationsEndpointPath: '/medications',
  integravidaProviderMedicationIntakesEndpointPath: '/medication_intakes',
  integravidaProviderAdverseEffectsEndpointPath: '/adverse_effects',
  integravidaProviderAlertsEndpointPath: '/alerts',
  integravidaProviderGlucoseRangesEndpointPath: '/glucose_ranges',
  integravidaProviderClinicalObservationsEndpointPath: '/clinical_observations',
  integravidaProviderDiagnosesEndpointPath: '/diagnoses',
  integravidaProviderClinicalReportsEndpointPath: '/clinical_reports',
  integravidaProviderAppointmentsEndpointPath: '/appointments',
};
