export const environment = {
  production: false,
  integravidaProviderApiBaseUrl: '/api/v1',
  integravidaProviderUsersEndpointPath: '/users',
  integravidaProviderPatientsEndpointPath: '/patients',
  integravidaProviderDoctorEndpointPath: '/doctor',
  integravidaProviderPatientDoctorEndpointPath: '/patientDoctor',
  integravidaProviderGlucoseRecordsEndpointPath: '/glucose-records',
  integravidaProviderSymtomsEndpointPath: '/symtoms',
  integravidaProviderMedicalHistoryEndpointPath: '/medicalHistory',
  integravidaProviderTreatmentsEndpointPath: '/treatments',
  integravidaProviderMedicationsEndpointPath: '/medications',
  integravidaProviderMedicationIntakesEndpointPath: '/medication_intakes',
  integravidaProviderAdverseEffectsEndpointPath: '/adverse_effects',
  integravidaProviderAlertsEndpointPath: '/alerts',
  integravidaProviderGlucoseRangesEndpointPath: '/glucose-ranges',
  integravidaProviderClinicalObservationsEndpointPath: '/clinical-observations',
  integravidaProviderDiagnosesEndpointPath: '/diagnoses',
  integravidaProviderClinicalReportsEndpointPath: '/clinical_reports',
  integravidaProviderAppointmentsEndpointPath: '/appointments',
};
