export const environment = {
  production: true,
  integravidaProviderApiBaseUrl: 'http://localhost:3000/api/v1',
  integravidaProviderUsersEndpointPath: '/users',
  integravidaProviderPatientsEndpointPath: '/patients',
  integravidaProviderDoctorEndpointPath: '/doctor',
  integravidaProviderPatientDoctorEndpointPath: '/patientDoctor',
  integravidaProviderGlucoseRecordsEndpointPath: '/glucoseRecords',
  integravidaProviderSymtomsEndpointPath: '/symtoms',
  integravidaProviderMedicalHistoryEndpointPath: '/medicalHistory',
  integravidaProviderTreatmentsEndpointPath: '/treatments',
  integravidaProviderMedicationsEndpointPath: '/medications',
  integravidaProviderMedicationIntakesEndpointPath: '/medication_intakes',
  integravidaProviderAdverseEffectsEndpointPath: '/adverse_effects',
  integravidaProviderAlertsEndpointPath: '/alerts',
  integravidaProviderGlucoseRangesEndpointPath: '/glucose_ranges',
  integravidaProviderClinicalObservationsEndpointPath: '/clinical_observations',
  integravidaProviderDiagnosesEndpointPath: '/diagnoses',
  integravidaProviderClinicalReportsEndpointPath: '/clinical_reports',
  integravidaProviderAppointmentsEndpointPath: '/appointments',
};
