export const environment = {
  production: false,
  integravidaProviderApiBaseUrl: 'https://integravida-backendservices.onrender.com',
  integravidaBackendApiBaseUrl: 'https://integravida-backendservices.onrender.com',
  integravidaBackendProfilesEndpointPath: '/api/v1/profiles',
  integravidaBackendAppointmentsEndpointPath: '/api/v1/appointments',
  integravidaProviderUsersEndpointPath: '/api/v1/authentication',
  integravidaProviderPatientsEndpointPath: '/api/v1/patients',
  integravidaProviderDoctorEndpointPath: '/api/v1/doctor',
  integravidaProviderPatientDoctorEndpointPath: '/api/v1/patientDoctor',
  integravidaProviderGlucoseRecordsEndpointPath: '/api/v1/glucose-records',
  integravidaProviderSymtomsEndpointPath: '/api/v1/symtoms',
  integravidaProviderMedicalHistoryEndpointPath: '/api/v1/medicalHistory',
  integravidaProviderTreatmentsEndpointPath: '/api/v1/treatments',
  integravidaProviderMedicationsEndpointPath: '/api/v1/medications',
  integravidaProviderMedicationIntakesEndpointPath: '/api/v1/medication_intakes',
  integravidaProviderAdverseEffectsEndpointPath: '/api/v1/medication-intakes',
  integravidaProviderAlertsEndpointPath: '/api/v1/alerts',
  integravidaProviderGlucoseRangesEndpointPath: '/api/v1/glucose-ranges',
  integravidaProviderClinicalObservationsEndpointPath: '/api/v1/clinical_observations',
  integravidaProviderDiagnosesEndpointPath: '/api/v1/diagnoses',
  integravidaProviderClinicalReportsEndpointPath: '/api/v1/clinical_reports',
  integravidaProviderAppointmentsEndpointPath: '/api/v1/appointments',
  integravidaBackendAdminEndpointPath: '/api/v1/admin',
  integravidaBackendDoctorEndpointPath: '/api/v1/doctors/me/patients',
};
